// apbenchfixtures materializes the §8.2 benchmark fixtures. The
// generated fixtures live under testdata/bench/{small,medium}/ and are
// NOT committed — `make bench-prepare` regenerates them deterministically
// so the repo stays small.
//
// Layout:
//
//	testdata/bench/small/   ~500 files, mostly Go, representative
//	testdata/bench/medium/  ~5,000 files — tests on dedicated hardware
//
// Both fixtures share the same module root + a regular directory
// branching factor, differing only in file count. Determinism matters
// here because CI diffs across commits must compare apples to apples.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type fixture struct {
	Name  string
	Files int
}

var fixtures = []fixture{
	{Name: "small", Files: 500},
	{Name: "medium", Files: 5000},
}

func main() {
	root := flag.String("root", "testdata/bench", "root directory for generated bench fixtures")
	only := flag.String("only", "", "comma-separated fixture names to generate (default: all)")
	flag.Parse()

	wanted := map[string]bool{}
	if *only != "" {
		for _, n := range splitCSV(*only) {
			wanted[n] = true
		}
	}

	for _, fx := range fixtures {
		if len(wanted) > 0 && !wanted[fx.Name] {
			continue
		}
		dir := filepath.Join(*root, fx.Name)
		if err := generate(dir, fx); err != nil {
			fmt.Fprintf(os.Stderr, "apbenchfixtures: %s: %v\n", fx.Name, err)
			os.Exit(1)
		}
		fmt.Printf("apbenchfixtures: wrote %d files under %s\n", fx.Files, dir)
	}
}

// generate writes the fixture tree. Files are deterministic: each
// fragment of content is derived from its index so a repeated run
// produces byte-identical output.
func generate(dir string, fx fixture) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := writeString(filepath.Join(dir, "go.mod"), "module example.com/bench/"+fx.Name+"\n\ngo 1.23\n"); err != nil {
		return err
	}
	if err := writeString(filepath.Join(dir, "README.md"), "# bench/"+fx.Name+"\n\nGenerated by apbenchfixtures. Do not edit by hand.\n"); err != nil {
		return err
	}
	if err := writeString(filepath.Join(dir, ".aperture.yaml"), "version: 1\ndefaults:\n  model: claude-sonnet\n  budget: 120000\n"); err != nil {
		return err
	}

	// Fan out files across ~10 packages so the AST parser sees a
	// realistic directory structure rather than one enormous flat dir.
	const pkgCount = 10
	for i := 0; i < fx.Files; i++ {
		pkgID := i % pkgCount
		pkgDir := filepath.Join(dir, fmt.Sprintf("pkg%02d", pkgID))
		if err := os.MkdirAll(pkgDir, 0o755); err != nil {
			return err
		}
		file := filepath.Join(pkgDir, fmt.Sprintf("file%05d.go", i))
		body := fmt.Sprintf(`package pkg%02d

// Sym%05d is an exported symbol populated by the bench fixture.
type Sym%05d struct{}

// Process%05d is a method exercised by AST extraction.
func (Sym%05d) Process%05d() int { return %d }
`, pkgID, i, i, i, i, i, i)
		if err := writeString(file, body); err != nil {
			return err
		}
	}
	return nil
}

func writeString(path, body string) error {
	return os.WriteFile(path, []byte(body), 0o644) //nolint:gosec // bench fixture files
}

func splitCSV(s string) []string {
	parts := strings.Split(s, ",")
	out := parts[:0]
	for _, p := range parts {
		if trimmed := strings.TrimSpace(p); trimmed != "" {
			out = append(out, trimmed)
		}
	}
	return out
}
